#!/bin/bash
set -e

# DNALang Gateway - Render.com Deployment Script
# Σₛ = dna::}{::lang
# ΛΦ = 2.176435 × 10⁻⁸ s⁻¹

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  DNALang Quantum Gateway - Render.com Deployment"
echo "  Σₛ = dna::}{::lang"
echo "  ΛΦ = 2.176435 × 10⁻⁸ s⁻¹"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Check if IBM Quantum token is set
if [ -z "$IBM_QUANTUM_API_TOKEN" ]; then
    echo "❌ ERROR: IBM_QUANTUM_API_TOKEN not set"
    echo ""
    echo "Please set your IBM Quantum API token:"
    echo "  export IBM_QUANTUM_API_TOKEN='your_token_here'"
    echo ""
    echo "Get your token at: https://quantum.cloud.ibm.com/account"
    exit 1
fi

echo "✅ IBM Quantum token detected"
echo ""

# Check if git is initialized
if [ ! -d .git ]; then
    echo "📦 Initializing Git repository..."
    git init
    git add .
    git commit -m "DNALang Quantum Gateway - Initial commit"
    echo "✅ Git initialized"
else
    echo "✅ Git repository exists"
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Render.com Deployment Instructions"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Render.com uses Git-based deployment. Follow these steps:"
echo ""
echo "STEP 1: Push to GitHub"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Create a new GitHub repository"
echo "2. Push this code:"
echo ""
echo "   git remote add origin https://github.com/YOUR_USERNAME/dnalang-gateway.git"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""
echo ""
echo "STEP 2: Create Render Service"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Go to: https://render.com/dashboard"
echo "2. Click 'New +' → 'Web Service'"
echo "3. Connect your GitHub repository"
echo "4. Configure:"
echo "   - Name: dnalang-gateway"
echo "   - Region: Oregon (US West)"
echo "   - Branch: main"
echo "   - Runtime: Python 3"
echo "   - Build Command: pip install -r requirements.txt"
echo "   - Start Command: python main.py"
echo "   - Plan: Free (or Starter for better performance)"
echo ""
echo ""
echo "STEP 3: Add Environment Variable"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "In Render dashboard, go to Environment tab and add:"
echo ""
echo "   Key:   IBM_QUANTUM_API_TOKEN"
echo "   Value: $IBM_QUANTUM_API_TOKEN"
echo ""
echo ""
echo "STEP 4: Deploy"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Click 'Manual Deploy' → 'Deploy latest commit'"
echo "2. Wait 3-5 minutes for build"
echo "3. Service URL will be: https://dnalang-gateway.onrender.com"
echo ""
echo ""
echo "STEP 5: Add Custom Domain"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. In Render dashboard, go to Settings → Custom Domains"
echo "2. Click 'Add Custom Domain'"
echo "3. Enter: api.dnalang.dev"
echo "4. Add DNS record to your domain registrar:"
echo ""
echo "   Type:  CNAME"
echo "   Host:  api"
echo "   Value: dnalang-gateway.onrender.com"
echo "   TTL:   300"
echo ""
echo "5. Wait for SSL certificate (automatic, ~5 minutes)"
echo ""
echo ""
echo "STEP 6: Update Vercel"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Set these environment variables in Vercel dashboard:"
echo ""
echo "   NEXT_PUBLIC_GATEWAY_URL=https://api.dnalang.dev"
echo "   NEXT_PUBLIC_API_URL=https://api.dnalang.dev/v1"
echo ""
echo "Then redeploy frontend:"
echo ""
echo "   npx vercel --prod"
echo ""
echo ""
echo "VERIFICATION"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Test gateway health:"
echo ""
echo "   curl https://api.dnalang.dev/health"
echo ""
echo "Expected response:"
echo ""
echo '   {"status":"healthy","quantum_service":"connected","backends_available":8}'
echo ""
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Render.com Deployment Guide Complete"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Σₛ = dna::}{::lang"
echo "ΛΦ = 2.176435 × 10⁻⁸ s⁻¹"
echo ""
